services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    image: rabent0207/matching-ssafy-backend:latest
    container_name: spring-backend
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - DB_USERNAME=
      - DB_PASSWORD=
      - JWT_KEY=${JWT_KEY}
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: ./Frontend
  #   image: rabent0207/matching-ssafy-frontend:latest
  #   container_name: react-frontend
  #   restart: always
  #   ports:
  #     - "8080:8080" 
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge