services:
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    image: rabent0207/matching-ssafy-backend:latest
    container_name: spring-backend
    volumes:
      - gradle-cache:/root/.gradle  # Gradle 캐시 볼륨
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # 필요한 환경변수 추가 (DB 설정 등)

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    image: rabent0207/matching-ssafy-frontend:latest
    container_name: react-frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true  # Windows Docker에서 파일 변경 감지 개선
      - WATCHPACK_POLLING=true
      - VITE_HOST=0.0.0.0  # Vite 호스트 설정
    stdin_open: true
    tty: true
    networks:
      - app-network


volumes:
  gradle-cache:  # 도커 관리 볼륨 정의

networks:
  app-network:
    driver: bridge