version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # 소스 코드 볼륨 마운트 (실시간 수정을 위해)
      - .:/app
      # node_modules는 컨테이너의 것을 사용 (성능상 이유)
      - /app/node_modules
      # shadcn/ui 설정 파일들 명시적 마운트
      - ./components.json:/app/components.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./src/lib:/app/src/lib
      - ./src/components/ui:/app/src/components/ui
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Windows Docker에서 파일 변경 감지 개선
      - WATCHPACK_POLLING=true
      - VITE_HOST=0.0.0.0  # Vite 호스트 설정
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 프로덕션 빌드 테스트용 서비스 (선택사항)
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    profiles:
      - prod-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# 개발 실행: docker-compose -f docker-compose.dev.yml up
# 프로덕션 테스트: docker-compose -f docker-compose.dev.yml --profile prod-test up frontend-prod