spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/team_ssearch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false  # ← 여기 수정!!
    properties:
      hibernate:
        format_sql: true
front:
  url: http://localhost:8081