server:
  forward-headers-strategy: framework # 스프링에서 프록시 전달 헤더를 자동으로 인식하도록 설정.

spring:
  security:
    headers:
      frame-options: DISABLE
    oauth2:
      client:
        registration:
          google:
            client-id: 191095046109-t21kv1o2632n6rou7pdi26isfkvht1eb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always  # 항상 초기화 스크립트 실행
      data-locations: classpath:data.sql  # data.sql 파일 위치 명시
      encoding: UTF-8  # 한글 깨짐 방지

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


jwt:
  secret: Nzg5ZjE0NzRlM2FjZjY4YzBkMTIzZmFhZjQ1NmY2ZDQ5YTc0MTg0MTNkZWIwZTkxY2YwYTc2ZTVjYmYzYjA3ZQ==
  expiration: 3600000 # 1시간 (ms)

front:
  url: http://localhost:8080

recsys:
  base-url: http://localhost:8000
  timeout:
    connect: 5s
    read: 30s


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    tryItOutEnabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-order-by-keys: true
