services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: spring-backend
    volumes:
      - gradle-cache:/root/.gradle  # Gradle 캐시 볼륨
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      # 필요한 환경변수 추가 (DB 설정 등)

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "18080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home  # 영구 저장
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data      # 영구 저장
      - sonarqube_logs:/opt/sonarqube/logs      # 로그 저장
      - sonarqube_extensions:/opt/sonarqube/extensions  # 플러그인 저장
    networks:
      - app-network

volumes:
  gradle-cache:  # 도커 관리 볼륨 정의
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  app-network:
    driver: bridge